on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches:
      - dev

name: Example
jobs:
  latest-version:
    name: Get Latest Release
    runs-on: ubuntu-18.04
    outputs:
      latest_image_timestamp: ${{ steps.latest_image_timestamp.outputs.timestamp }}
      latest_release_timestamp: ${{ steps.latest_release.outputs.latest_tag_published_at }}
      latest_release_name: ${{ steps.latest_release.outputs.latest_tag }}
    steps:
    - name: Get the timestamp of the latest image on Docker Hub
      id: latest_image_timestamp
      run: |
        echo "::set-output name=timestamp::$(curl -L --silent https://registry.hub.docker.com/v2/repositories/orbsmiv/shairport-sync-rpi/tags/latest | python3 -c "import sys, json; print(json.load(sys.stdin)['last_updated'])")"
    - name: Get Latest Upstream Release
      id: latest_release
      uses: abatilo/release-info-action@v1.1.0
      with:
        owner: mikebrady
        repo: shairport-sync

  docker_buildx:
    runs-on: ubuntu-18.04
    needs: latest-version
    if: github.event_name == 'push' || needs.latest-version.outputs.latest_release_timestamp > needs.latest-version.outputs.latest_image_timestamp
    steps:
      - name: test-output
        run: |
          echo "Version ${{needs.latest-version.outputs.latest_release_name}} was released at ${{needs.latest-version.outputs.latest_release_timestamp}}"
          echo "Latest tag published at ${{needs.latest-version.outputs.latest_image_timestamp}}"
          echo "Release is newer than image. Build required."
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.6.1
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Run Buildx (no push-to-hub)
        run: |
          docker buildx build \
          --platform linux/arm/v7 \
          --output "type=image,push=false" \
          --build-arg "SHAIRPORT_VER=${{needs.latest-version.outputs.latest_release_name}}" \
          --tag orbsmiv/shairport-sync-rpi:${{needs.latest-version.outputs.latest_release_name}} \
          --tag orbsmiv/shairport-sync-rpi:latest \
          --file ./Dockerfile \
          .
      - name: check built version
        run: |
          docker run --rm \
          --entrypoint /usr/local/bin/shairport-sync \
          orbsmiv/shairport-sync-rpi:${{needs.latest-version.outputs.latest_release_name}} \
          -V
          

