on:
  schedule:
    - cron: "*/15 * * * *"

name: Example
jobs:
  latest-version:
    name: Get Latest Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Latest Release
      id: latest_version
      uses: abatilo/release-info-action@v1.1.0
      with:
        owner: mikebrady
        repo: shairport-sync
    - name: Example of consumption of the output
      env:
        LATEST: ${{ steps.latest_version.outputs.latest_tag }}
        LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
      run: |
        echo "Version $LATEST was released at $LATEST_DATE"
